/* eslint-disable jsx-a11y/alt-text */
import React from "react";
import FooterPagePro from "../Footer/Footer";
import HomeHeading from "../HomeHeading/HomeHeading";
import Navbar from "../Navbar/Navbar";
import './Pro13.css'
function Pro13 ()
{
    return(
    <>
    <HomeHeading/>
    <Navbar/>
    <div className="BodyPro13">
         <div className='HeaderPro13'>
             <img src={require('../../Images/img_13_1.jpg')} />

         </div>
         <div className='MainPro13'>
             <p>We at RUDRAKSHA, are working under the Project Name “AAROGYA” under the Project Head “VIGOUR AND VITALITY”, offering free medical consultations, check-ups and medicines from certified doctors of ayurvedic, homoeopathic, and allopathy medicinal cultures. The World Health Organisation defines health as a state of mental, physical, and social wee being, and not merely physical well-being. Individuals who are healthy in mind are automatically healthy in their bodies. Good health is the man’s greatest possession. A healthy person is one who can function up to his optimal capacity without any difficulty. Good health facilitates a lot of other body processes. Good health helps us to handle stress and combat with increasing pressures. Health can be of varied varied types, physical, emotional, mental social, and spiritual health. Distress can cause neurotic disorders, and healthy people are less likely to fall prey for them. Physical health refers to the bodily well being of individuals. It involves maintaining a healthy lifestyle. An individual follows a balanced diet, replenished with carbohydrates, proteins, fats, vitamins and minerals, in adequate quantities, usually has better immunity. Health is wealth means good health is the real treasure. A healthy life enables one to remain positive and face all life challenges.</p>
             <img src={require('../../Images/img_13_2.jpg')} />
             <p>Physical health requires few dedicated efforts, including regular exercise and consumption of a lot of water. Water regulates all our body processes, reduces chances for zits and pimples, and ensures regular bowel movements. Exercises like brisk walking, cycling, and skipping help in maintaining proper body weight. Mental health refers to our emotional and psychological well-being. Mental health has a significant impact on our thoughts, behaviours and attitude. It is essential to give equal attention to our mental health as its effects are grave. Society has a significant impact on individual’s mental health. It is essential to create a positive environment around yourself to courier the negativity. Cutting off toxic people is the right away of having better mental health. Above everything, we must choose happens and optimism as the guiding principles of our life. Health and Medicine encompasses the study of the prevention, cure and understanding of disease as well as the investigation of physical and mental well-being.
             “Children’s Quality of Life Declining,” the headline said. A study from the Foundation for Child Development noted that more than 21% of American children were living in poverty in 2010, up 5% from 2006 and the highest rate in two decades. Child experts warned that the increasing poverty could impair children’s health. The sociologist who led the study worried that child obesity could increase as families were forced to move away from more expensive health food to processed and fast food. A child psychology professor said that people who grow up in poverty have higher rates of cancer, liver and respiratory disease, and other conditions. The president of the American Academy of Paediatrics agreed that family poverty is a health risk for children, who are more likely to be born prematurely and/or with low birth weight and to develop asthma and other health problems as they grow. She added that all these problems can have lifelong effects: “The consequences of poverty build on themselves, so that the outcomes can be felt for years to The fact that our social backgrounds affect our health may be difficult for many of us to accept come".</p>

             </div>
             <div className="Main2Pro13">
                 <p>Whether someone suffers a serious illness is often simply a matter of bad luck or bad genes: we can do everything right and still become ill. In saying that our social backgrounds affect our health, sociologists do not deny any of these possibilities. They simply remind us that our social backgrounds also play an important role. Importance of health and medicine has enhanced the life expectancy of human beings. For last hundred years' medicinal processes and medical equipment are proved to be the boon to human health for diagnosing properly and for applying proper medicines to the patient. Medicine has opened a reliable method of curing and protecting human lives. It showed the various ways of diagnosing the diseases of human beings.</p>
                 <img src={require('../../Images/img_13_3.jpg')} />
                 <p>The coronavirus pandemic has sent shockwaves to the health system, societies, and economies around the world. The healthcare sector is at the epicenter of this unprecedented global pandemic challenge and the pandemic is likely to cost huge to the health sector. Though private hospitals are extending full support to the government in terms of equipment, isolation wards, and workforce, the health industry is bound to face challenges. The pandemic has decreased the surgeries, international patients, and OPD footfall. It will impact the cash flows of hospitals as 80% of the costs are fixed. That apart, the crisis has hit hard the medical devices industry. The situation in China has disrupted the exports of critical raw materials and the export of medical devices. Governments all over the world work towards providing good quality healthcare for their people. Creating awareness about health issues, ensuring strong infrastructure, and promoting health insurance are productive activities conducted by the authorities for people’s welfare. The Indian Government also undertakes such measures from time-to-time.
                 Ayushman Bharat scheme came into existence because of recommendations made by the National Health Policy. Ayushman Bharat Yojana is designed keeping in mind Universal Health Coverage (UHC). Health services in India are largely segmented and Ayushman Bharat aims to make them comprehensive. It is about looking at the health sector as a whole and ensure continuous care for the people of India. Aam Aadmi Bima Yojana is meant for people involved in certain vocations such as Carpentry, Fishing, Handloom weaving, etc. There are 48 such defined vocations. Before 2013, there were two policies of similar nature, AABY and Janashree Bima Yojana (JBY). After 2013, JBY was merged with AABY. The premium for Rs.30000 insurance policy is Rs. 200 for a year. The eligibility criteria for this policy is that one should be a family head or an earning member of one’s family (around the poverty line) and should be performing one of the 48 mentioned vocations.</p>
             </div>
             
             <div className="Main3Pro13">
             <p>Aawaz Health Insurance Scheme is a health insurance cover for migrant workers and is initiated by the Government of Kerala. It also offers insurance for death by accident for labourers. The scheme was launched in the year 2017 and targeted 5 lakh inter-state migrant labourers working in Kerala. The health insurance coverage offered under Awaz Health Insurance is Rs.15000, while the cover for death is Rs.2 lakh. Central Government Health Scheme (CGHS) is initiated by India’s Central Government. Central Government employees are eligible for this policy. For example, Supreme Court judges, Certain Railway Board employees, etc. This policy has been active for six decades and has covered more than 35 lakh employees and pensioners. Hospitalization, as well as domiciliary care, are covered as per this plan’s terms and conditions. Central Government Health Insurance Scheme covers Allopathy and Homeopathy as well. It is available in 71 cities and the plan is to expand the scope to more areas.</p><br/>
             <img src={require('../../Images/img_13_4.jpg')} />
             <p>Karunya Health Scheme is directed towards providing Health Insurance for listed chronic illnesses. It is a Critical Illness plan for the poor and covers major diseases such as Cancer, Kidney Ailments, Heart-related medical issues, etc. Those below or near the poverty line can enrol themselves for this cover. Aadhaar Card and appropriate Income Certificate are needed for this scheme. There were rumours that this scheme has been abolished, however, they were just rumouring as this scheme is still active. Pradhan Mantri Suraksha Bima Yojana came into existence to offer accident insurance to the people of India. In 2016, it was observed that only 20% of the Indian citizens had an insurance cover. However, Pradhan Mantri Suraksha Bima Yojana aspires to change this statistic in a positive manner. People aged 18 to 70 and having a bank account can avail of the benefits of this scheme. This policy offers an annual cover of Rs. 1 lakh for partial disability and Rs. 2 lakhs for total disability/death for a premium of Rs. 12. The premium gets debited automatically from the insured person’s bank account.Universal Health Insurance Scheme schemes for the benefit of their poor people. In India, the Universal Health Insurance Scheme aspires to do that and much more. This scheme can be availed by the poorest of the poor in the age group of 5 to 70 years. It offers individual as well as group insurance. It covers hospitalization, accident, and disability. The premium varies as per the size of the family. Those falling under the poverty line need to show proper documentation to avail the policy.
            
            We at RUDRAKSHA, are trying to give full health support to the needy people. Many people are below the poverty line, live in rural areas and poor who cannot even afford to take care of health. Those individuals who are working in small factories, often get ill and health issues. For those of people living in rural areas and slum areas are not aware of how to take care of health, they are not having even correct amount of protein, nutrition, the children too often get ill, and due to unawareness and not having adequate money, these people die. So, we will try to support these people like, poor, rural people, slum people and who are alone and help them in taking care of health and providing them medicines for their diseases. Also, to open free medication centres at Schools, Societies and providing them free medicines like, allopathic, ayurvedic and homeopathic medicines as per the doctor’s recommendation. We will also set up free eye check up centres for the needy ones. We will try to support in various medical tests such as MRI, CT Scan, Blood tests, etc., and arranging ambulance for the needy ones.</p> </div>
    </div>
            

    <FooterPagePro/>
    </>)}
export default Pro13