import React from 'react'
import './Agenda.css'
import Navbar from '../Navbar/Navbar';
import HomeHeading from '../HomeHeading/HomeHeading';
import FooterPagePro from '../Footer/Footer';
function Agenda() {
  return (
      <>
      <HomeHeading/>
    <Navbar/>

    <div className='BodyA4'>
            <div className='HeaderA4'>
                <img src={require('../../Images/AGENDA.jpg')} />


            </div>
            {/* <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Note:</strong> We don’t appreciate offers for money laundering, Fake CSR bills or Reports. Kindly refrain from contacting us for such activities. Your wisdom and support in this will be highly appreciated.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div> */}

            <div className='A1'>
                <p>We at RUDRAKSHA, have a well defined journey with a prime motive to achieve success in making dreams come true for all those people around us who are lagged behind due to several personal and other challenges in their respective lives. The Foundation will work together along with them to fulfill their professional dreams & other legitimate needs with a prime motive of allowing them to enrich and relish equal respect, dignity, health, earnings, better standard of living and confidence in their day to day lives. The mission of this Foundation will be completely unbiased and will act on first come first serve or first noticed first serve basis. The recommendations from any individual or group to provide any sort of legitimate help or assistance to anyone in the 15 Projects as per named mentioned below will be highly appreciated. These Activities will be requiring good amount of funds as well as technically enriched manpower to handle all projects. The Foundation will be working on self sustainability model along with support from various Govt. as well as Private Organizations PAN INDIA. The objective will not be stressed upon to raise funds from the CSR bucket of the various prestigious organizations, but will be raising funds through providing premium quality goods and services to general public at very reasonable rates in comparison to the prices quoted by several other respected players in the market. The respective Government Rules, Regulations and Licensing for the same will be procured well in advance before initiating any such business or activity of the nature as applicable.</p>
                            <p>A strict compliance will be applied on the business ethics of the Foundation with a prime motive to earn minimum profits as compared to other respected players in the so called business activity and Funds or profits earned will be directed only towards the philanthropy and self sustainable activities of the Foundation. The initialization of the Foundation humanitarian actions will be conducted in various Schools, Colleges, Sub Urban and Rural areas, BPL population, etc. with adequate support sought from paper, digital media, advertisements, and documentaries with a prime motive to engage like minded people available to support our cause and help millions of unknown friends on this planet. Foundation will follow a strict compliance in respect to raise Funds from legitimate sources only hence there will be NO CASH DONATIONS accepted by anyone in this organization from any individual or group. The Funds raised will be only through legitimate means like Demand Drafts, Cheque, Fund Transfers, IMPS, E-wallets, and Payment Applications as approved by RBI with the help of a payment Gateway as registered with this website on donation Page. We will be working as per the guidelines drafted in UN Sustainable Development Goals in comparison to the working areas of this Foundation’s reach. We will try to follow the guidelines and suggestions provided by experts in the field of CSR and Social Welfare to the maximum possible extent as per the situation and circumstances of the Foundation in the concerned area of our social activities.</p>
            </div>

            <div className='A2'>
                {/* <img src={require('../Images/Img2.jpeg')} /> */}
                {/* <p>The completion of the assigned targets with dignity and ethics can provide them to attain such benefits and hence will boost up their career progression as well. The Foundation also supports enhancement of technical and non technical education/training of its employees hence provide them an opportunity to attain the same while working with us. We also provide financial and non financial support for the same, provided the employee should have the matching of the concerned training or course program in respect to his/her job requirements and career progression. The Final decision will be reserved with MD of the organization. This benefit can be attained post completion of probation period. The basic requirement for a white color job in this organization is an ethical bachelor’s degree from any recognized University though a profile specific might require an additional or specific degree in the same field. The list of address and Identity proofs required will be same as per guidelines applicable for any Govt or Private jobs PAN INDIA. Any Job in this Foundation, by any means or at any point of time WILL NOT BE A GOVT or SEMI GOVT or GOVT / SEMI GOVT CONTRACTUAL job in respect to benefits, culture, process, settlements, rights etc. by any sort or means whatsoever be the case. THIS WILL BE SAME AS A PRIVATE ORGANIZATION and respective rules and regulations are mentioned in website & or Code of Conduct in respect to the position held by an individual. The applicants are requested to read and understand them carefully. The Foundation will not be held responsible for any sort of loss occurred due to it. The queries before applying for any job opening will be appreciated on phone or email. WE DON’T ASK FOR CASH OR ANY SORT OF KIND FAVORS FOR ANY JOB. In case there will be an opening, the same might be issued in public interest to apply via local or national based job or internship portals, companies, agencies, our websites, other job web links etc. but there will not be any charges applicable for the same by any sort of means at any stage in future unless specifically mentioned in our website. Kindly REFRAIN from getting in touch with any individuals or companies who asks for commissions or salary portions etc. for jobs posted at our website. Anyone can apply for them directly.There are no charges for applications. The candidates will be shortlisted post personal interview session (s) and verification checks.</p> */}
                <p> The Foundation will work in liaison with various States and Central Government policies, plans and Schemes with an objective to support the targeted areas of the Government for social up-liftment and higher standards of living for the fellow citizens of our prestigious INDIA. We will be working along with several Government agencies in order to act efficiently as and when required.
                 A support will be sort from various individuals and organizations in case their presence in the targeted audience will be helping us to leave a positive and efficient mark in their development and living enhancement.This Foundation will always be striving for maximum utilization of resources available in the most efficient manner in order to support the Economical Health and a strict compliance will also be followed to Transparency of the various goods and services that will be sought for self sustainability measures as well as social work associated activities from various vendors in each sector of the society. The social work conducted by this Foundation will be brought into the knowledge of the stakeholders’ as well general public through the help of fortnightly reports flashed on our website. </p>
                 <p>The data captured by us will be used only for the activities of this Foundation for which it has been created and will never be sold or rented to any other individual or group as such for their personal benefits. The data though will be presented to Government Departments or Agencies as and when demanded or wherein we feel any need to submit it with respected Govt. authorities. The Foundation will be following a religious compliance to proper Planning and procurement of all the resources and permissions required before conducting any activity at a given point of time in general as well specific in nature. The goods and services procurement will be done with the most economical way possible at a given stage and proper records of all the expenditures and respected invoices will be uploaded on the website. We will be highly supportive to the Feedback being provided to by general public and will be properly digitally documented in our website for our future enhancement and guidance. We will be giving complete importance to Impact Assessment actions as conducted internally along with targeted audiences as well as other agencies as and when required.</p>
            </div>
{/* 
            <div className='MainAU3'>
                <img src={require('../Images/Img3.jpeg')} />
                <p>The jobs in this Foundation requires good amount of public dealings and interactions hence individuals applying for the same are expected to be well known to Hindi, English and Punjabi. The initial work profile will be in Chandigarh and in due course will be expanded to various States of North INDIA. The general working hours in this Foundation will be between Monday to Friday 9:30 am – 6:00 pm during summer and 9:30 am to 5:30pm during winters. There will be working ours based on any activity if being scheduled on Saturdays or any other holidays as per the case may arise. The employee will be benefited with an additional off day within next 45 -60 days from the day he or she had made her contribution on any holiday or weekends. The working rules will be applicable on the domestic as well as International official tours. The travel expenses for official trips will be borne by our Foundation. Our Foundation puts an extra emphasis over Gender Equality parameters, hence we hire close to 50% female employees in our projects and in general. The actual number may vary depends upon meeting financial and other work profile constraints. The detailed eligibility requirements of all the above mentioned benefits and processes are listed in “Code of Conduct” column in this website. We might involve other organizations, NGOs in our project(s) based on the need arises as per the situation. The preference will be through well established organization on State, Center or National Level which have positive track records. A strict compliance and due diligence will be followed as setup by Government for philanthropy organizations.</p>
            </div> */}

        </div>
        <FooterPagePro/>
        </>
  )
}

export default Agenda