import React from 'react'
import FooterPagePro from '../Footer/Footer'
import HomeHeading from '../HomeHeading/HomeHeading'
import Navbar from '../Navbar/Navbar'
import "./Pro8.css"

function Pro8() {
  return (
      <>
      <HomeHeading/>
      <Navbar/>
    <div className='BodyPro8'>
            <div className='HeaderPro8'>
                <img src={require('../../Images/header8.jpg')} />


            </div>
            {/* <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Note:</strong> We don’t appreciate offers for money laundering, Fake CSR bills or Reports. Kindly refrain from contacting us for such activities. Your wisdom and support in this will be highly appreciated.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div> */}

            <div className='MainPro8'>
                <img src={require('../../Images/img1pro8.jpg')} /> 
                <p>We at RUDRAKSHA, are working under the Project Name “AVSHTAMBH” under the Project Head “OLD AGE, BLIND HOMES AND ORPHANAGES”, focussing on basic needs, health care, emotional and religious support to senior citizens homes, blind homes and orphanages. There is one Acharya more than ten Upadhyas, father is more than hundred Acharyas and mother is more than a thousand times prouder than father. In both the above verses, the glory of parents, gurus and superior people is clear. These three are our direct deities. Therefore, it is our duty to serve these souls with their bodies, minds and wealth, it is our religion to always keep them satisfied and happy. Apart from Manusmriti, in our other religious texts, parents, gurus and best people have been considered venerable. It is the duty of all of us to keep these three happy forever. To care for someone who once cared for us is the highest honour. Getting old is an inevitable process. It is inherent to human being. And with old age comes maturity, wisdom and respectability. Elderly people are precious. They are the revered members of our family, wise sages and keeper of traditions. They are a goldmine storehouse of knowledge. Caring for the elderly aids to self-development. Old-age is a time when they need help in things, they effortlessly do by themselves before. It is a time when they need attention and affection.</p>
                <p>Elderly are the truest form of wisdom. They have lived for a long time- from generations to generations. They teach us respect, perseverance, wisdom. By being with them and caring for them establish relationships. We learn patience and tolerance by caring for them. As they have lived long, they know life very well. We learn how to face problems- we learn everyone have to face problems and anyone can overcome it. They teach us to look at things in a deeper level rather than waddling in the shallow pool. Elderly helps us to see people as well as ourselves differently- in a good way. There teach us that that there is so much more to things as well as people than they appear. We become more self-aware and wiser through all the things they teach and do. Through their actions we imbibe better the seeds they sown. Through their calmness and serenity from all the experiences and lessons they have learnt and gathered through the years they provide us a better platform for us follow and imitate as actions speak louder than words. Caring for them benefits us in many ways and prepares us to face life and overcome it. All the little things that we learnt through caring strengthens us and help us to live life in fulfilment and satisfaction; storing all the things that we learnt and doing it. Still we are forcing our parents and elder people to go and live in a old age home. They are our family; they have raised us, give us an identity and we are giving them this result by leaving them alone because they do not understand our generation. Elderly teach us the value of family, relationships and life. As humans are industrious being- we don’t like to feel stagnant. We love progress. And through progress we win. Caring for the elders help us to grow in many ways which altogether lead to who we are. We owe to them. We will not be here if it were not for them. It is everyone’s responsibility to grow into a respectable elder- someone whom we can go to for help and counsel. And as no man is an island and he is constantly shaped and influenced by the experience of life he goes through, it is very important that he get the right experience and counsel by being with the diamonds, and storehouse of wisdom and goodness- the elderly!</p>

            </div>

            <div className='Main2Pro8'>
                <p>Pradhan Mantri Vaya Vandana Scheme is one of the most popular senior citizen pension schemes in India. Designed for senior citizens above 60 years of age, the policy term of this Prime Minister Senior Citizen Scheme extends to ten years. They can earn interest of 8% per annum over this scheme. Indira Gandhi National Old Age Pension Scheme is specially intended for older adults above the age of 60 years, who fall below the poverty line, according to the guidelines prescribed by the Government of India. National Programme for the Health Care of Elderly was introduced in 2010, this scheme concentrates on preventive as well as promotive care for the maintenance of overall health. This program was launched to address the health issues faced by seniors. Varishta Mediclaim Policy aids seniors by covering the cost of medicines, blood, ambulance charges, and other diagnosis related charges. Designed for senior citizens between the age of 60 and 80 years, this helps meet the health-related expenses of senior citizens.</p>
            <img src={require('../../Images/img2pro8.jpg')} /> 
            <p>Senior Citizens Welfare Fund launched by the Ministry of Social Justice and Empowerment, this fund includes unclaimed amounts from small savings and savings accounts in the Central government schemes. It aims to make seniors financially stable for their overall welfare and health care. There is nothing denying in the well said quote; If love is blind, then maybe a blind person that loves has a greater understanding of it. A blind person will not thank anyone for a looking glass but will definitely pass on the blessings from his soul for all those actions you have taken to make that person life shining like a diamond with dignity and ethics. Close your eyes and try to do something you do every day, like putting toothpaste on a toothbrush. You will soon realise how difficult it is to do things if you cannot see what you are doing. People who cannot see face such difficulties every day. They depend on their other senses (touch, smell, sound and taste) to learn about the world around them. And, with practice, they learn to use these senses better than people with sight.</p>
            <p>One of the things the blind cannot do is read ordinary books. So, they learn to read books printed in Braille. Braille is a system of representing characters by raised dots. Combinations of raised dots in a six-dot ‘cell’ make up different characters. Blindness does not stop people from doing great things. Surdas, the famous poet and saint, was blind. The English poet John Milton dictated his best-known work (Paradise Lost) after he became blind. Eyes donation has also become an important thing. Various people are in a practice to donate their organs after their death. Eyes are the most essential part which needs to be fixed within a stipulated time. Eyes must be removed within 6 hours of death and should be covered with cotton so that it does not catch the moisture. It only takes 10-15 minutes to remove without leaving any scar. Many people used the cornea of dead people for their training and teaching purposes, so, in 2008, Maharashtra issued a circular regarding the prohibition of sharing cornea for teaching or training purposes. There is a need of Cornea because there are 6 million people who are blind and amongst them only 25,000 go under cornea transplant.</p>
             </div>

            <div className='Main3Pro8'>
               <p>Around 20,000 cases are adding every year. Divyangjan Swavalamban Yojana Scheme for Persons with Disabilities scheme is to assist the needy disabled persons by providing concessional loan for economic and overall empowerment. The blind person may not be present at the station for purchase of the ticket, prescribed form, from a government doctor, is eligible to get the concession. Under the scheme, handicapped children are sought to be integrated in the normal. Being an Orphan is a lethal pain that cuts down the life of any human being at any stage of his life and this very well describes the agony, pain, scare, demotivation for all those unfortunate children who don't have Parents either from the time they are born or later during young age. Their eyes always look out for those Honest, Graceful, Dignified, True & Loveable Seniors who can provide them love, care, Affection, Attention & Security. Throughout our world, hundreds upon thousands of children are kept in orphanages. These children, who have no home, no parents, and no siblings to play with, are kept in a place where all they have left is their childhood; and even that is taken away from them in these living hells. Most people would define the word orphanage as a public or private institution for the care and protection of children without parents.</p>            
               <img src={require('../../Images/img3pro8.jpg')} /> 
               <p>According to UNICEF, almost 10,000 children become orphans every day. According to internationally accepted figures, there are at least 140 million orphans in the world. Given the fact that there is so much compelling evidence showing that there are millions of more orphans not included in official statistics, there is no doubt that this number is actually much higher. Orphans who have lost both parents in a hostile action, and became orphan before the age of 37, will be entitled to a benefit and advantages, by virtue of one parent, under the Compensations for Victims of Hostile Actions Law. Until age 21, an orphan is entitled to a survivor’s pension by virtue of the second parent, under the Old Age and Survivors Law. And when it comes to adopt orphans, our country has shameful record on adoption. We have more than 30 million orphans in the country, but when it comes to adopt only 2500 orphans were adopted last year.</p>
               <p>We at RUDRAKSHA, will try to help old people, orphans and persons with physical disabilities. For the old people we will try to help them in availing pension benefits and can help them by providing them the things they need, like clothes, books, spending time with them, arranging various games at old age homes, overall good environment, etc. and try to help them in providing them various needy things like, television, medicines. For the blind people we can try and help them out in terms of providing education, visiting blind homes and spending time with them. Also, we can try to provide them some special books, games, and items that are meant for them only. For orphans, we will try to help the orphan children to provide them education, food, clothes, spending time with them, taking them on picnic, and any help if required.</p>
            </div>

        </div>
        <FooterPagePro/>
        </>)
}

export default Pro8
