/* eslint-disable jsx-a11y/alt-text */
import React from "react";
import FooterPagePro from "../Footer/Footer";
import HomeHeading from "../HomeHeading/HomeHeading";
import Navbar from "../Navbar/Navbar";
import './Pro12.css'

function Pro12 ()
{
    return(
        <>
        <HomeHeading/>
        <Navbar/>
        <div className='BodyPro12'>
        <div className='HeaderPro12'>
            <img src={require('../../Images/img_12_1.jpg')} />
        </div>

        <div className='MainPro12'>
                <p>We at RUDRAKSHA, are working under the Project Name “ADDHYAN” under the Project Head “TRUE WISDOM DEVOTEES”, to provide no cost coaching of various subjects for students up-till higher secondary levels in respect to basic education. Mahatma Gandhi says, “Genuine education does not consist of cramming a lot of information and numbers in mind. It not only lies in passing the examination by reading a number of books, but it lies in developing character. It is a real education which inculcates internal virtues (values) in human beings. If you can develop such virtues, it will be the best education”. Education is a process of comprehensive development of the best things lying in the mind and soul of children or men and bringing them out. Gandhiji shows us and to the world to observe and implement the lofty virtues and daily life practices by setting an example of himself by putting in to practice those ideals in hid daily life activities. Education aims at creating ideal citizens. Ideal refers to an individual, who is overwhelming with virtues and is always well mannered.</p>
                <img src={require('../../Images/img_12_2.jpg')} /> 
                <p>Idol citizens are the pre-requisites for coherent and comprehensive development. Also, it aims to produce best citizens means the education of the hearts of people and expects to change their hearts. Value education means the education that teaches to put the virtues and values in to practices. The values presented by the National Education of Commission and NEP 1986, states morality, sympathy and spiritual development education. Primary education is the basic and important right of every child. Its availability and provision are not only the responsibility of state but parents and households. It brings out the awareness among the masses, opens avenues for opportunities as well self-advancement and improvement and reduces chronic and inter-generation poverty. In order to tackle and compete the world, children are prepared from the childhood days, as early as for or five years old, the children grew up in the home, where they seek advice from their parents, family and learn how to interact with people in outer world. General or basic education in various disciplines play an important role for children.
                Primary education is compulsory for students on life, where all the related disciplines the basic knowledge and necessary, which may include counting, word formation and understanding of general ethics, norms and standards of knowledge around. Primary education is usually started before, in some countries, such as nursery classes in other countries is the first step. It ends up at 10 years old as fifth grade students. Other than this discipline the most important aspect is secondary education to strengthen the vocational education in the former stream. 67% of children (age 6-10 years) go to school 57% literacy rate. Thousands of trained teachers are needed in order to provide education to the children. There are so many reasons due to which children can’t go to school. Their parents can’t afford school fees, uniforms and books. Most of the communities do not have enough resources to run a school. At most of the rural places or villages, schools are at a very long distance which make children to avoid them and specially for girls. In different cultural practices, boy gets priority than girls when it comes to education. Girls are kept at home to help with house dos and do not get the same freedom as boys. It is important for the Government of India to make extra efforts by running more programs and educational priotized policies to achieve Millennial Education Development Goals set under the declaration signed in 2000.</p>

                </div>
                <div className="Main2Pro12">
                    <p>With the formulation of National Policy on Education, India initiated a wide range of programmes for achieving the goal of UEE through several schematic and Programme interventions such as- Sarva Shiksha Abhiyan (SSA) is a Government of India’s flagship programme for achievement of Universalisation of Elementary Education (UEE) in a time bound manner, as mandated by 86th amendment to the Constitution of India making free and compulsory Education to the children of 6-14 years age group, a Fundamental Right. SSA is being implemented in partnership with State Governments to cover the entire country and address the needs of 192 million children. This programme seeks to open new schools in those habitations which do not have schooling facilities and strengthen existing school infrastructure through provision of additional class rooms, drinking water, and school improvement grants.SSA seeks to provide quality elementary education including life skills. SSA has a special focus on girl’s education and children with special needs. SSA also seeks to provide computer education to bridge the digital divide.</p>

                </div>

                <div className="Main2Pro12">
                     <img src={require('../../Images/img_12_3.jpg')} /> 
                    <p>Mid-day Meal Programme was introduced for disadvantaged children in Madras Municipal Corporation. By the mid-1980s three states i.e. Gujarat, Kerala, Tamil Nadu, and the UT of Pondicherry has universalized a cooked Mid-Day Meal Programme with their own resources for children studying at the primary stage and the implementing this programme with their own resources on a universal scale. Mahilla Samakhya Programme was launched in 1988 to pursue the objectives of the National Policy Education, 1986. It recognised that education can be effective tool for women’s empowerment, the parameters of which are enhancing self-esteem and self-confidence of women, building a positive image of women by recognising their contribution to the society, developing ability to think critically, ensuring equal participation in development processes, and providing information, knowledge and skill for economic independence.
                    National Program for Education of Girls at Elementary Education (NPEGEL) has been initiated by Government of India to reach girls, especially the girls that are not enrolled in school. The program was started in July 2003 and this program is a significant component of the SSA. The program provides extra support for improving the education of girls. Some objectives that come under this scheme are the development of learning materials that are gender-sensitive, gender-sensitisation of teachers, provisions like stationary, uniforms, and workbooks. The main focus of this program is to break gender stereotypes and to make sure girls get a good education at the elementary level. Beti Bachao Beti Padhao scheme initiated in 2015 is one of the most famous central government schemes for girl education. The main aim of this government scheme was initially to protect girl children from female foeticide and infanticide and later, provide assistance for their education. The Beti Bachao, Beti Padhao scheme ensures the protection of girls and their survival and makes sure that girls participate in educational activities alongside boys. This scheme thus spreads the awareness that girl children are not a burden. Rashtriya Madhyamik Shiksha Abhiyan was launched in March, 2009 with the objective to enhance access to secondary education and to improve its quality. The implementation of this National Vocational Education Qualification Framework scheme is presently under revision to address the issue of enhancement of employability of youth through competency based modular vocational courses, to maintain their competitiveness through provision of multi entry and multi exit learning opportunities and vertical mobility. National Means Cum-Merit Scholarship Scheme (NMMSS) was launched in May 2008. The objective of the scheme is to award scholarships to meritorious students economically weaker sections to arrest their drop out at class VIII and encourage them to continue the study at secondary stage.</p>
                 </div>
                 
                <div className="Main3Pro12">
                <img src={require('../../Images/img_12_4.jpg')} />
                    <p>The students studying in Kendriya Vidyalya are not entitled to get scholarship under this scheme. NCERT acknowledges and appreciates educational brilliance in students through the National Talent Search Scheme.It also seeks to applaud artistic distinction through the Chacha Nehru Scholarships - for artistic and innovative excellence. The National Bal Bhawan has instituted a system of honouring talented children in different age groups in the year 1995 through the Bal Shree scheme. The goal of achieving universal primary education is especially important because educational attainment has been noted as a key aspect to overall economic growth.Basic education can be very important in helping people to get jobs and gainful employment. This economic connection, which is always present is very critical in a rapidly globalising world in which quality control and production according to strict specification can be crucial. Yet basic education in all the societies is critical to individual and economic development and political stability and it also contributes to improved health, human rights and gender equity.More than 775 million people over the age of 15 are illiterate. That is the 17 percent of the world’s adult population. Our main aim is to strengthen the capacity of communities to support basic education and literacy, reduce gender disparity in education and increase adult literacy. We support education for all the children and literacy for children and adults.
                    
                We at RUDRAKSHA, is also trying to educate the students who cannot afford school books, uniform, or the student is a girl child, school is not near, etc. We will try to help those children, who want to study but can’t do so because their parents are not able to afford the expenses like fees, books, uniform, stationary, so we will provide them all necessary things they need and make their children study to endeavour in future prospects. Also, we will try to provide the free of cost tuitions by our experts to the weak students, who are not able to fully gasp the content taught in the class, or they need some sort of revision. We can also do one thing to provide them online learning, since all the rural places and villages have 4G connectivity, so the tuitions can be provided over the online platform. If there is no school or any available resources through which the children can study then an alternative, we can do is to install a smart television or a computer in one of the houses of the village i.e. the Panchayat or the head of the village, and all the children in that village can join in there house and can get education online through our experts. They can also be provided with online learning if they have 4G connectivity at there place.</p>

                </div>
        
                 

        </div>
        <FooterPagePro/>
        </>)}

export default Pro12