import React from 'react'
import FooterPagePro from '../Footer/Footer'
import HomeHeading from '../HomeHeading/HomeHeading'
import Navbar from '../Navbar/Navbar'
import "./Pro10.css"

function Pro10() {
  return (
      <>
      <HomeHeading/>
      <Navbar/>
    <div className='BodyPro10'>
            <div className='HeaderPro10'>
                <img src={require('../../Images/header10.jpg')} />
            </div>

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Note:</strong> We don’t appreciate offers for money laundering, Fake CSR bills or Reports. Kindly refrain from contacting us for such activities. Your wisdom and support in this will be highly appreciated.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            <div className='MainPro10'>
                <p>We at RUDRAKSHA, are working under the Project Name “RUDRASHAKTI” under the Project Head “TRUE ETERNAL WARRIORS”, to support the families of defence personals, who have made the sacrifice for the nation. “When a warrior serves in the military, his or her entire family serves and sacrifices as well. Military families need the support of the government and our nation to ensure their needs are met.” Soldiers are one of the greatest assets of any country. They are the guardians of the nation and protect its citizens at all costs. Moreover, they are a very selfless lot who put the interest of the country above their personal interest. A soldier’s job is one of the toughest things to do in the world. They are supposed to fulfil challenging duties and possess exceptional qualities to become a great soldier. However, their lives are very tough. Nonetheless, they always fulfil their duties despite the hardships.</p>
                <img src={require('../../Images/img1pro10.jpg')} /> 
                <p> A country sleeps peacefully as the soldier performs its duties. The first and foremost duty of a soldier is to serve their country without any selfish motive. A person usually joins the army out of love for his motherland and to protect it. Even though they know they will have to face numerous problems, they still do so for their country. Furthermore, a soldier safeguard’s the honour of his country. They do not step back in the face of adversaries instead they give their best. It does not matter if they have to give their life for the country, they are willing to do so happily. Besides, soldiers also have to be alert at all times. He is never off duty, whether he is sleeping or on the battlefield, he stays vigilant throughout. Most importantly, a soldier’s duty is to maintain the peace and harmony of the country. He takes on the responsibility of ensuring a safe environment for all. In addition to guarding the border, they are also always there in case of emergencies. They learn how to handle every situation carefully whether it is a terrorist attack or natural calamity. In other words, the local authorities need them to bring the situation under control. Being a soldier is not easy, in fact, it is one of the most challenging things to do. Their lives are full of hardships and challenges which no ordinary person can survive. Firstly, they spend a great deal of time away from their loved ones. It disturbs them emotionally and they do not even get any holidays. Even in festivals, they are busy safeguarding the nation. Similarly, soldiers have to undergo rigorous training to become fit to fight battles. It becomes exhausting and physically challenging, but they still go on. To make it worse, they do not even get an adequate amount of supply to lead a normal life. Sometimes, the food rationing is low, the other times they get posted in remote areas without any signal. The effective intelligence and reasoning ability of the soldiers make them a valuable weapon. Their strict regime makes it possible for them to remain in complete health and with unmatched stamina. The fact that their own families and work for the nation is what gives them an unmatched reputation.</p>
            </div>

            <div className='Main2Pro10'>
                <p>Subsequently, they also have to make do in the harshest of weather conditions. It does not matter if it is scorching hot or chilling cold, they have to be out on the battlefield. Similarly, they do not even get enough bulletproof equipment which will keep them safe. Thus, we see what a challenging life our soldiers lead to protect their country.what is a glorious adventure for you, is a daily routine for us”. This is the statement that holds the amount of utmost truth. We as regular citizens learn rifle shooting as sport, where the soldiers play with their lives holding them daily. Climbing mountains, staying intents, and not eating a home-cooked meal is an adventure for us where we feel fresh, but this thrill is multiplying by the fear of losing their own lives in the battlefield. Recently a violent face off took place between Indian and Chinese soldiers in Ladakh’s Galwan Valley in which 20 Indian solders were killed. Rajnath Singh quoted “loss of Indian soldiers at Galwan Valley is deeply disturbing and painful and India will never forget the bravery and sacrifice of the soldier’s exemplary courage and valour in the line of duty and sacrificed their lives.</p>
            <img src={require('../../Images/img2pro10.jpg')} /> 
            <p>The attack on CRPF convoy in Jammu and Kashmir Pulwana, killed 40 soldiers on February 14, is the biggest terror attack in the past five years. However, data released by the Narendra Modi government on February 5, 2019 reveal that Jammu and Kashmir has been witnessing regular terror attacks in the past five years. We live in a nation where our soldiers are day and night, in a very worse weather stand and fight for the people of the nation and make them sleep peacefully at night. They are being martyred on the borders by the terrorists. And we live in a society where we respect them much, but after 3-4 days by having a lot of discussion, social media posts, news reporting, everyone forgets about them. We don’t think about their families, what are they going up to, now how will they spend their lives. Instead of just of sitting at home and gossiping how their families will live, we can come forward to provide help to their widows by giving them a source of income and providing education help to children. Since 2016, the number of terrorist incidents has seen an upward trend. For example, the number of terrorist incidents in Jammu & Kashmir rose by 54.8 per cent in 2016, six per cent (342 incidents) in 2017, and 79.53 per cent (614 incidents) in 2018. In fact, the year 2018 saw nearly 51 terrorist incidents every month. Between 2014 and 2018, a total of 1,315 people was killed in the state due to terrorism. Of these, 138 (10.49 per cent) were civilians, 339 (25 per cent) security personnel, and 838 (63.72 per cent) were terrorists.</p>
            </div>
            <div className='Main4Pro10'>
                <p>Our nation was attacked once more by four terrorists near town of Uri in the state of Jammu and Kashmir and it was one of the deadliest attacks on security forces in Kashmir. Many soldiers were killed from the 10th battalion and 6th battalion. We have seen news about the various data sources, and according to the data by Parliament there has been witnessed suicide deaths of soldiers between 2011-18. These soldiers are on the one side fighting for the nation on the border and on the other hand, they are fighting with their mental health too. There has been average of 88 suicide deaths annually and defence forces are strict actions to cut down this issue.</p>
                <img src={require('../../Images/img3pro10.jpg')} /> 
                <p>The data released by the Ministry of Home Affairs shows that between 2014 and 2018, there has been a 93 per cent rise in the number of security personnel killed in terrorist incidents in Jammu and Kashmir. Besides this, these five years also saw a 176 per cent rise in the number of terrorist incidents in the state. In this period, the state suffered a total of 1,708 terrorist incidents (on an average, the 28 terrorist incidents every month for five years), the government data reveal. The home ministry said that in 2014, there were 222 terrorist incidents in the state. This figure saw a marginal decrease the next year (2015) when there were 208 such incidents. Every family life has its up and downs. Life for members of an armed forces family, whether they're regulars, reservists, or veterans, or their spouses, partners or children, can have additional worries. There are a number of organisations, in addition to NHS services, armed forces families can go to get the advice and support they may sometimes need. The Navy, Army and RAF all have their own welfare support organisation and information services. There are other organisations and charities that may be able to offer assistance and provide additional welfare services. Soldiers, Sailors, Airmen and Families Association (SSAFA) is the national charity supporting service personnel, veterans and their families. SSAFA offers support to the community, whether at home, overseas or in an operational environment. Defence Medical Welfare Service (DMWS) is a registered charity that works for the MoD and with other charities to provide practical and emotional support to military personnel, their families and other entitled civilians when they're in hospital, rehabilitation or recovery centres.</p>
                <p>We at RUDRAKSHA, will try our level best to cater to all the legitimate needs of our martyred soldier's families by providing them a helping hand in earning their livelihoods through dignity. We will try to provide them offer to make pottery items, clothes, bags, decor items and most regularly Food orders will be placed with them in order to conduct free food services in their local areas; where in ration, gas etc will be provided by us and post consumption per plate charges will be paid to them. We will try to assist them in regular tiffin services as well. An offer can be made for educated individual widows to go for online or in person teaching sessions along with self-study certifications if required by them at our expense. We will also try to support the existing soldiers in terms of medical help, education for their children, and legitimate legal help.</p>
            </div>

        </div>
        <FooterPagePro/>
        </>)
}

export default Pro10
