import React from 'react'
import FooterPagePro from '../Footer/Footer'
import HomeHeading from '../HomeHeading/HomeHeading'
import Navbar from '../Navbar/Navbar'
import "./Pro4.css"

function Pro4() {
  return (
      <>
      <HomeHeading/>
      <Navbar/>
    <div className='BodyPro4'>
            <div className='HeaderPro4'>
                <img src={require('../../Images/header4.jpg')} />
            </div>

            {/* <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Note:</strong> We don’t appreciate offers for money laundering, Fake CSR bills or Reports. Kindly refrain from contacting us for such activities. Your wisdom and support in this will be highly appreciated.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div> */}

            <div className='MainPro4'>
                <p>We at RUDRAKSHA, are working on the Project Name “SOOKASHAM RAKSHNAM” under the Project Head “ENVIRONMENT ARMOUR”, concentration of care and plantation of existing and new trees in society and road side. We, have a firm belief of making as much contribution as we could with the help of society towards setting up clean and healthy surroundings as that could be the best gift we would be able to handover to our upcoming generation as whole. This objective will for sure be in progress religiously beyond “World Environment Day, 5th June”. The hard core facts are staring at our face which depicts the harsh reality of a severely damaged and pollute environment as now a days we are keener towards acquiring latest gadgets and machine without giving a single bit of thought towards cleaning our locality and setting up trees and plants which will be more essentially required for our future generations. We all can quote ourselves an example of our life style as on today in comparisons to the one we had been living since our childhood. We had enjoyed lots of greenery in our locality and cities till the time we had been stuck vigorously with globalization of each sector of our Economy. The tremendous increase in the number of production plants, vehicles, real estate etc. sectors have brutally killed billions of trees in and around our cities.</p>
                <img src={require('../../Images/img1pro4.jpg')} /> 
                <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Let’s begin discussing what Government and Laws have setup for all of us to follow which in general we make sure to mess it up partially or completely even in our daily lives. The Environment (Protection) Act, 1986 authorizes the central government to protect and improve environmental quality, control and reduce pollution from all sources, and prohibit or restrict the setting and /or operation of any industrial facility on environmental grounds. The Environment (Protection) Act was enacted in 1986 with the objective of providing for the protection and improvement of the environment. It empowers the Central Government to establish authorities charged with the mandate of preventing environmental pollution in all its forms and to tackle specific environmental problems that are peculiar to different parts of the country. The Act was last amended in 1991. The Environment (Protection) Rules lay down procedures for setting standards of emission or discharge of environmental pollutants. The objective of Hazardous Waste (Management and Handling) Rules, 1989 is to control the generation, collection, treatment, import, storage, and handling of hazardous waste. It was introduced with a view to protect the environment, nature, and health, in connection with the application of gene technology and micro-organisms. The Biological Diversity Act 2002 and Biological Diversity Rules provide for the conservation of biological diversity, sustainable use of its components, and fair and equitable sharing of the benefits arising out of the use of biological resources and knowledge associated with it. Under the National Green Tribunal Act 2010 for effective and expeditious disposal of cases relating to environmental protection and conservation of forests and other natural resources including enforcement of any legal right relating to environment and giving relief and compensation for damages to persons and property and for matters connected therewith or incidental thereto. The Tribunal's dedicated jurisdiction in environmental matters shall provide speedy environmental justice and help reduce the burden of litigation in the higher courts. The Noise Pollution (Regulation and control) (Amendment) Rules, 2010 states to reduce noise pollution, permit use of loud speakers or public address systems during night hours (between 10:00 p.m. to 12:00 midnight) on or during any cultural or religious festive occasion. The Municipal Solid Wastes (Management and Handling) Rules, 2000 is applied to every municipal authority responsible for the collection, segregation, storage, transportation, processing, and disposal of municipal solid wastes. The Biomedical waste (Management and Handling) Rules,1998, is a legal binding on the health care institutions to streamline the process of proper handling of hospital waste such as segregation, disposal, collection, and treatment.</p>
            </div>

            <div className='Main2Pro4'>
                <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The National Environment Appellate Authority Act, 1997, has been created to hear appeals with respect to restrictions of areas in which classes of industries etc. are carried out or prescribed subject to certain safeguards under the EPA. “The matter of grave concern is despites so many Acts in place when will we as humans start ACTING to save our precious Mother Earth as its already too late for our Environment to spare us by any sort. “ We have been struck with serious health issues of lungs, liver, kidneys, heart, eyes etc. and there is nothing denying the fact that our bad and polluted environment is the major contributor in the same. The real fact is whatever we had given to the Mother Nature, she had reciprocated the same to us but in a more dangerous and destructive way.</p>
            <img src={require('../../Images/img2pro4.jpg')} /> 
            <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Corona virus/ Covid-19 undoubtedly has put every country in lockdown. Several lakh had lost their lives; but apart from the deadly condition all around, the beneficiary had shown in the improvement of environment. By no traffic on road, less contribution to air pollution, slow down in the process of releasing waste in oceans by large industries. Finally, nature takes its breath. As quoted by Francois Gemenne, director of the Hugo Observatory “Strangely enough, I think the death toll of the corona virus at the end of the day might be positive if you consider the deaths from atmospheric pollution,". ‘If we want to live better , we need to treat our nature better’. This is the only message by nature for us. Since this lockdown has started in the month of march in India till now the data of pollution has decreased. After like many years we took breath in clean atmosphere. Birds are flocking back and its really beautiful to get close to mother nature.</p>
            </div>

            <div className='Main3Pro4'>
                <p>Covid19 pandemic effect on carbon emission:-</p>
                <ul>
                    <li>Traffic congestion with less number out people out of their home leads to less pollutants like carbon monoxide.</li>
                    <li>Agreeing to this, that airways hit hard by this pandemic but greenhouse gases declined. According to UN aviation it was said that in 2018, airplane emission of carbon was reached 900 million tons and to be doubled by 2025. But this has also taken a turn.</li>
                </ul>
                
                <p>Covid19 pandemic impact on waste:-</p>
                <ul>
                    <li>Medical waste- as the demand of disposable medical product increases with single uses it has create a deluge of medical waste.</li>
                    <li>Reusable packaging is increasing in use during this phase, no report regarding packaging food causes transmit disease has shown yet.</li>
                </ul>  
            </div>

            <div className='Main4Pro4'>
                <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We hereby would like to request each and every individual who is reading these notes to please don’t stop after reading this infect be a valuable contributor in the plantation of more and creed more trees and post plantation taking due care of them in order to have a better clean and healthy environment not only for us but for the entire society. We are lucky that our mother nature is unbiased. We will be happy to assist you donating trees and be a partner with us in the plantation of maximum number of trees and plants in our locality as well as homes and offices in general. We proudly salute people like “Peepal Baba, who had given their entire life towards mother Earth and has planted more than 1 crore Peepal Trees PAN INDIA. Life expectancy in India has increased from 49.7 years in 1970-75 to 68.7 years in 2012-16, as per the National Health Profile 2019.</p>
                <img src={require('../../Images/img3pro4.jpg')} /> 
                <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The We as human race should never forget the our basic need of food and oxygen which is being provide by plants and trees we have enriched in our planet Earth. We have already crossed the danger mark and still millions of people are not awake and still busy in earning money and making careers at the cost of the lives of their children and themselves. The respected public figures like Bollywood personalities, Sports personals, Theatre Artists, Senior Govt. officials, Corporate Heads, Social Entities will be involved in Environmental Activities. A routine compliance will be followed in order to make our surroundings clean and making sure due diligence is applied by people living in the area to keep it clean and healthy as per the guidelines of “SWACH BHARAT ABHIYAAN”. We will also thrive towards using of vacant land spaces under MC or individuals, which have been kept vacant since a long time spam to be converted into a land wherein plants and trees can be planted in order to have a better environment. A major activity will also be conducted to plant trees on both sides of the NH4 highway, which connects us with Capital and several cities in between.The respected Ministry of Road Transport and Highways as well as Ministry of Environment, Forest and Climate Change (MoEFCC), guidance and help will enrich the activity manifolds. We are quite sure none of the Parents will love to see their old age Parents, their children and themselves to be dependent of Artificial Oxygen and strict medicine compliance on daily basis. Water on this Planet is also a serious concern and if wastages of it is not being controlled today collectively by us then it is quite sure by the end of 2030, most of the States in INDIA will have a serious life threatening status in respect to underground water level as well as drinking water. The RO’s waste tons of water and by the end of 2030 we will face the problem. We will also strive forward to make sure the dependency of single use plastic items to be removed from the day to day lives of the people in general wherein they can be replaced with either a decomposable plastics as guided by GOI and making them dependent on Cloth and Jute bags which will be distributed by our Foundation at regular intervals in all the Schools of our city and where ever this could be possible in the future to come. We might involve other organizations, NGOs in this project based on the need arises as per the situation.</p>
            </div>

        </div>
        <FooterPagePro/>
        </>)
}

export default Pro4
