/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable no-unused-vars */
import React from "react";
import FooterPagePro from "../Footer/Footer";
import HomeHeading from "../HomeHeading/HomeHeading";
import Navbar from "../Navbar/Navbar";
import './Pro15.css'

function Pro15()
{
    return(
        <>
        <HomeHeading/>
        <Navbar/>
        <div className="BodyPro15">
            <div className="HeaderPro15">
            <img src={require('../../Images/img_15_1.jpg')} />
                
             </div>
            <div className="MainPro15">
                <p>We at RUDRAKSHA, are working under the Project Name “PRANIKA” under the Project Name “WOMEN EMPOWERMENT”, with a motive to enhance the educational, basic rights, health, skill development and social personal security. Women Empowerment itself describes us the with most Hippocratic situation of our society as in with the grave desire to give her the right to Education, Safety, Economic Stability, Equality and Health when we consider her Goddess Saraswati, Goddess Durga Goddess Lakshmi, Goddess Parvati and Goddess Gayatri respectively in our Holy books. In case we could have understood the true meaning of a women in our lives, we would not have been staged at a place where in one of the most precious creature of God has been put under cages of ignorance, illiteracy and economic dependability. Women are the soul of a house, a society, a nation and world in a pure context, whether living in a shape of human body or Mother Nature hope are aware of it except on 8 th March every year being “Women’s Day”. We have unfortunately left no stone unturned to hit her with most dreadful situations in today’s lives and time had already passed wherein she will be caged in the clutches of ignorance and fear. We at RUDRAKSHA, have a soul belief to assist her in attaining something which was originated by her as a matter of cosmic wisdom and nurture her to the best possible way as a respect gesture.</p>
                <img src={require('../../Images/img_15_2.jpg')} />
                <p> The prima facie evidence on Women Empowerment now days has been a dire need of hour even directed by United Nations guidance protocol for all Countries. It has been directed to make equal participation and opportunities for women whether it is social economic or political scenarios as a whole. It has already been directed to focus making a change in the situation on war front for providing education, health, safety and economic stability of women in our country. Government have already started on a big front in making equal opportunities for women in each and every field and even on the path of making the reservations for them in field of Education, Health facilities, Transportation, Politics, Jobs and new Laws have already been incorporated which in turn assures Women’s Safety as the top most agenda. The recent shocking situations occurred in our Country with respect to Women Safety is a matter of grave concern not only for Govt. but for all of us to make way through which the same can be stopped is to incorporate Strict and Rigid laws which are enough to send cold shivers to such criminals. Women Empowerment is nothing less than providing them their basic human rights with a assurance of better and safe life in future.
                Almost every country, no matter how progressive has a history of ill-treating women. In other words, women from all over the world have been rebellious to reach the status they have today. While the western countries are still making progress, third world countries like India still lack behind in Women Empowerment. In India, women empowerment is needed more than ever. India is amongst the countries which are not safe for women. There are various reasons for this. Firstly, women in India are in danger of honor killings. Their family thinks its right to take their lives if they bring shame to the reputation of their legacy. Moreover, the education and freedom scenario is very regressive here. Women are not allowed to pursue higher education; they are married off early. The men are still dominating women in some regions like it’s the woman’s duty to work for him endlessly. They do not let them go out or have freedom of any kind. Women Empowerment directly helps the society in making a control over Fake Feminism as recently a justice prevails for social media sensation lad name Mr. Sarvjeet Singh a resident from Capital, who has been helped by none other than female book writers and Men Rights activists.</p>
            </div>
            
            <div className="Main2Pro15">
                <p>We should keep such live examples in our thought process before revoking the rights for women at any place in our lives. The need of women empowerment is not limited to the boundaries of a house or office but infect have an impact on the society and nation on a larger picture which directly resembles the future of upcoming generations even before their birth. The concept is simple and crystal clear as in you take due care of the women surrounding you in your daily lives and they will keep on performing their duties likewise since ages. The balance and dignity is the core concept and should be favored and respected in all forms of lives.</p> <br/>
                <img src={require('../../Images/img_15_3.jpg')} />
                <p>The Government has already framed a dignified “NATIONAL POLICY FOR THE EMPOWERMENT OF WOMEN (2001), which protects the principle of gender equality as enshrined in the Indian Constitution in its Preamble, Fundamental Rights, Fundamental Duties and Directive Principles. The Constitution not only grants equality to women, but also empowers the State to adopt measures of positive discrimination in favor of women. The primary objective of this policy is to make sure women social and economic rights to be protected with utmost diligence with the help of several women organizations. They give immense stress over women intervention in making decisions related to social and economic decisions of the society and nation in a bigger framework. These objectives can be positively completely only if women should end up their taboo relating to limited thought process when it comes to society and their families. Government has always put stress over eliminating the gender discrimination and changing the social attitudes and communal practices which puts hindrances in women enhancements in various sectors of the society.
                In several countries round the globe preferably in our INDIA, the condition of women have considerably improved when it comes to super mega projects by GoI like “Beti Bachai Beti Parahao”, “Poshan Abhiyaan”, “One Stop Centre Scheme”, “Women helpline scheme”, “Working Women’s Hostel (WWH)”, “SWADHAR Greh Scheme”, “Pradhan Mantri Mantru Vandana Yojana”, “Rajiv Gandhi National Creche Scheme”, “Mahila e-Haat, “Mahila police volunteers” “National Mission for Empowerment of Women (NMEW)”, “Pradhan Mantri Mahila Shakti Kendra scheme”, “Rastriya Mahila Kosh (RMK)”, “NAND-GHAR YOJANA”, “Pradhan Mantri Ujjwala Yojana”, “Maternity Benefit Program”, “Sukanya Samriddhi Yojana”, “eSamvad portal” , “Nari Web Portal”, “She-Box Portal” and “New Draft National Policy”. These schemes have already impacted several lives positively wherein when they have no way to look for help as per dire situations in their personal as well as professional lives.</p>
            </div>
            
            <div className="Main3Pro15">
                <p>Mahila E-haat is a direct online marketing platform launched by the Ministry of Women and Child Development to support women entrepreneurs, Self Helf Groups (SHGs) and Non- Governmental Organisations (NGOs) to showcase products made and services rendered by them. This is a part of the 'Digital India' initiative. Beti Bachao, Beti Padhao is a social campaign aimed at eradication of female foeticide and raising awareness on welfare services intended for young Indian girls. The "Save the Girl Child" movement was launched on 22 January 2015, it is a joint initiative run by the Ministry of Women and Child Development, the Ministry of Health and Family Welfare and the Ministry of Human Resource Development. To bridge the growing gap between the birth of girl and boy infants, the government of India has taken up an initiative to promote Beti Bachao Beti Padhao and many programmes has been organized to promote ‘Save Girl Child' and to ‘Educate Girl Child', since January 2015. The campaign has also received support from the Indian Medical Association.</p>
                <img src={require('../../Images/img_15_4.jpg')} />
                <p> One Stop Centre Scheme Popularly known as 'Sakhi,' it was implemented on 1st April 2015 with the 'Nirbhaya' fund. The One Stop Centres are established at various locations in India for providing shelter, police desk, legal, medical and counselling services to victims of violence under one roof integrated with a 24-hour Helpline. The toll-free helpline number is 181. Working Women Hostels- The objective of the scheme is to promote the availability of safe and conveniently located accommodation for working women, with daycare facility for their children, wherever possible, in urban, semi-urban, or even rural areas where employment opportunity for women exist. The Support to Training and Employment Programme for Women (STEP) Scheme aims to provide skills that give employability to women and to provide competencies and skill that enable women to become self-employed/ entrepreneurs. A particular project will be for a duration of up to 5 years depending upon the nature, kind of activities and the number of beneficiaries to be undertaken.
                The Nari Shakti Puruskars are national level awards recognizing the efforts made by women and institutions in rendering distinguished services for the cause of women, especially vulnerable and marginalized women. The awards are presented by the President of India every year on 8 March, International Women's Day at Rashtrapati Bhavan in New Delhi. Women have a major impact over globalization of the economy as their basic rights if not nurtured properly in their favor will lead to breakdown of the economic policies and impacts the Nation from Environment to Agriculture, Health to upcoming generations, industry to Laws, Science & Technology to Home Science. We all have definite target to achieve in this concept and media plays a vital role in upbringing the women security, development, motivation, individuality and entitlements. We would be trying our best in helping the women from all phases of lives in the areas of health, sanitation, education, children welfare, medical facilities, and skill development. These projects will be undertaken with the help of Government and Private agencies, individuals, corporate etc. only through legitimate sources of funds as approved under rules and regulations by GOI. The main stress will be provided to Health, Education and Self Defense Training of Women and girls. The respected officials from Govt. as well as private sector will be involved for guidance and contribution in this philanthropy action towards building a sound future.</p>
            
            </div>
            
            <div className="MainPro15">
                <p> We might involve other organizations, NGOs in this project based on the need arises as per the situation. The preference will be through well established organization on State, Center or National Level which have positive track records. A strict compliance and due diligence will be followed as setup by Government for philanthropy organizations.</p>
            </div>
         
         
        </div>

        <FooterPagePro/>
        </>)}
export default Pro15