/* eslint-disable jsx-a11y/alt-text */
import React from "react";
import FooterPagePro from "../Footer/Footer";
import HomeHeading from "../HomeHeading/HomeHeading";
import Navbar from "../Navbar/Navbar";
import "./Pro11.css"
function Pro11()
 {
    return (
        <>
        <HomeHeading/>
        <Navbar/>
      <div className='BodyPro11'>
              <div className='HeaderPro11'>
                  <img src={require('../../Images/header11.jpg')} />
              </div>
              
              <div className='MainPro11'>
                <p>We at RUDRAKSHA, are working under the Project Name “AACHARYA” under the Project Head “TRAINING SKILL DEVELOPMENT”, to provide training and knowledge to the students of various streams as well as professional grooming. Training and Skill Development is a major part of human lives since their birth, though the same has been followed religiously by all the living organisms on this planet. The Skill Development Activity is being initiated since very early age in the life of a social as well non social animal anywhere in this universe. This is the core element of one’s development, strength, stability, preference and above all entity. The higher the quality, lucrative will be the success tagline, not only in professional as well as day to day lifestyle.</p>
                <img src={require('../../Images/img11pro11.jpg')} /> 
                <p> The same has been followed since ages during GURUKUL ERA, till now a days with the importance and requirement has been increased manifolds this date. The importance of Skill Development can easily be measured as comparisons are being done with warriors like ARJUNA, KARAN, and EKLAVYA. In our country still today our Trainers, Teachers; Coaches have a dream of achieving any student who falls under anyone of the above category. Now a day’s Government is also quite serious about Skill Development of Youths in order to provide them with best learning opportunities and conducive environment to nurture their skills and make their careers. UNESCO also have a Skill Development Mission and in line to the same celebrate a World Skill Development Day on July 15 every year. The National Skills Development Corporation (NSDC) facilitates initiatives that can potentially have a multiplier effect as opposed to being an actual operator in this space. In doing so, it strives to involve the industry in all aspects of skill development. There are several programs run under flagship of NSDC, and an overview about the same is listed below from the respected Government web portals. Pradhan Mantri Kaushal Vikas Yojana (PMKVY) is the flagship scheme of the Ministry of Skill Development & Entrepreneurship (MSDE) implemented by National Skill Development Corporation. The objective of this Skill Certification Scheme is to enable a large number of Indian youth to take up industry-relevant skill training that will help them in securing a better livelihood. Individuals with prior learning experience or skills will also be assessed and certified under Recognition of Prior Learning (RPL). Pradhan Mantri Kaushal Kendra is a scheme under which Vocational training needs to be made aspirational to transform India into the skill capital of the world. In line with the same, Ministry of Skill Development and Entrepreneurship ( MSDE ) intends to establish visible and aspirational Model Training Centres ( MTCs ) in every district of the country. NSDC is the implementation agency for the project. Udaan, the Special Industry Initiative (SII) for J&K is funded by Ministry of Home Affairs and implemented by National Skill Development Corporation (NSDC). The programme is a part of the overall initiative for addressing economic issues in J&K. While steps are being taken by the State and Central Government to revive economic activity in J&K, Udaan programme is a special initiative to address the needs of the educated unemployed in J&K. Udaan program is focused on youth of Jammu & Kashmir (J&K) who are graduate, post graduate and three year diploma engineers. The aim is to provide skills and job opportunities to the youth. India International Skill Centers (IISCs) were set up through the National Skill opportunities to the youth.</p>
               </div>
            <div className='Main2Pro11'>
                <p>India International Skill Centers (IISCs) were set up through the National Skill Development Corporation (NSDC) with the objective to provide skill training and certification bench marked to International Standards to facilitate overseas mobility of Indian workforce for jobs. Ministry of Skill Development and Entrepreneurship (MSDE) provided support for domain training and Ministry of External Affairs (MEA)is providing support for Pre-Departure Orientation Training (PDOT) under the Pravasi Kaushal Vikas Yojna (PKVY) framework. TITP, commenced in 1993 in Japan, aims to contribute to developing countries by accepting people from these countries and transferring skills through an On-the-Job-Training. In October, 2017, India had joined hands with Japan by signing a Memorandum of Cooperation on TITP. NSDC has been appointed as the ‘Implementing and Monitoring Agency’ for TITP by the Ministry of Skill Development and Entrepreneurship, Government of India.</p>
            <img src={require('../../Images/img_11.jpg')} /> 
            
            <p> Training presents a prime opportunity to expand the knowledge base of all employees, but many employers in the current climate find development opportunities expensive. Training from the skilled and qualified Trainers in their respective battle fields is the only easiest and safest possible solution. Employees attending training sessions also miss out on work time which may delay the completion of projects. Despite the potential drawbacks, training and development provides both the company as a whole and the individual employees with benefits that make the cost and time a worthwhile investment. Training has a direct result of improved employee performance, satisfaction and morale. It also addresses their weaknesses, expands their consistency and have an in depth impact on their Increased productivity and adherence to quality standards. Training also increases innovation in new strategies and products and reduces employee turnover which directly enhances company reputation and profile. We hence had incorporated this activity in the top priority lists of Philanthropy actions on regular intervals. The Trainers have been incorporated from their respective domains from PAN INDIA, who have a successful career in their areas of expertise and will be requested to impart their knowledge into the fresh and dynamic brains of our youngsters. This will finally help them in making a developed career in their field of interest which will finally helps us in contributing towards the building of a sound future for our Nation as a whole.

            The modus operandi of this activity will be based on total funds collected from the sales of goods and services from general public and implementing the same in the Training Sessions for desired and needy candidates from various sections of the society irrespective of any caste, creed, religion, gender or any other sort of discrimination. The model applicable will be First Come First Serve basis. We will be conducting the Training Programs under the guidance of experienced Trainers and modules will be designed with their approvals and as per the requirements of the Skill Development Parameters of Today’s world. The Training Institutes from State, Central as well Private (Approved) centers will be requested to be our partners in this act of Social Skill Development Programs at regular intervals. The candidates will be allowed to submit their applications either with their respective Schools, Colleges, Universities and Training Institutes who are associated with us in this Program. The Individuals are also welcomed to be a part of the same and sessions will be held either at recognized centers, Schools, Colleges, Hotel Conference Rooms or at our premises. A due diligence will be provided to candidate’s behavior during the Training Program as well as their attendance and feedback from respected Trainers</p>
            </div>
            <div className='Main4Pro11'>
                <p>The respected Parents of the desired candidate (in case of minor) will be updated on daily basis about the presence and performance of the candidate in order to make sure they comply with strict rules and regulations. A Certificate from the recognized and approved Institute will be offered to the candidate at the end of the Program post their submission of respective Project work and Examination. The entire procedure will be online and details of the result will be shared with the respected Parents in due course along with the candidate. The Scholarship will be offered to the respected candidate as per their need and can vary between 50% - 100% of Training Program Cost. The Organization might try to take care of the stay, food and travel of the outstation candidates as the case may arise. The Training will be in online as well group discussion mode as per the module design. A strict compliance will be followed in respect to number of candidates per group. We will be bearing the total cost of the Training from respective Institutes and Professionals as decided before the beginning of the programme.</p>
                <img src={require('../../Images/img_pro.jpg')} />

                <p> The different Skill Development Program that will be conducted by Recognized and Approved Centers under this head are as follows: A structured training and development program ensures that employees have a consistent experience and background knowledge. The consistency is particularly relevant for the company's basic policies and procedures. The training may also build the employee's confidence because she has a stronger understanding of the industry and the responsibilities of her job. This confidence may push her to perform even better and think of new ideas that help her excel. The investment in training that a company makes shows the employees they are valued. The training creates a supportive workplace. A development program brings all employees to a higher level so they all have similar skills and knowledge. This helps reduce any weak links within the company who rely heavily on others to complete basic work tasks. The short listing of the Institutes, Universities and Colleges for conducting such programs will be done which have either being a part of Government Bodies or have a quality module with most effective costing in a Private sector. The candidates will be provided all the details along with their Parents (in case of minor) and a written consent before their enrollment in the concerned program. The Foundation will be offering such approved courses through Authorized Institutes to the weaker section of the society who either approaches us or we came to know about their need to attain knowledge of such Advocacy Programs. We will also participate aggressively in the general public awareness programs which are related to Health, Life Safety, Human Rights, Consumer Rights, Voting Rights, Various Government Schemes & Programs Awareness etc. The prime objective is to assist the needy in getting his rights within due course of time and without any corruption.</p>
                <p>We at RUDRAKSHA, have a firm belief stating in order to flourish in an individual life, once has to work hard and keep themselves up to date with effective knowledge byes that are required by our profession and career enhancement basic criteria. We can learn a lot from our surroundings as well as work culture, ethics, society and role model, but in order to implement the same into our professional as well as professional lives, we have would require a skill to use the same knowledge to perfection. We will also be approaching several State and Central Government Bodies and Ministries for guidance and support in our activities in order to achieve maximum coverage. The directives shown to us will not only help us in achieving the social targets of our Foundation but will also help us in reaching to the maximum number of people. We are quite hopeful of such precious and in time support from our respective Government Agencies and Bodies in the firm and sound future building for our Nation and its Citizens. We might involve other organizations, NGOs in this project based on the need arises as per the situation. The preference will be through well established organization on State, Center or National Level which have positive track records. A strict compliance and due diligence will be followed as setup by Government for philanthropy organizations.</p>
            </div>

              
      </div>
      <FooterPagePro/>
      </>)}

      export default Pro11