import React from 'react'
import FooterPagePro from '../Footer/Footer'
import HomeHeading from '../HomeHeading/HomeHeading'
import Navbar from '../Navbar/Navbar'
import "./Pro5.css"

function Pro5() {
  return (
      <>
      <HomeHeading/>
      <Navbar/>
    <div className='BodyPro5'>
            <div className='HeaderPro5'>
                <img src={require('../../Images/header5.jpg')} />
            </div>

            {/* <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Note:</strong> We don’t appreciate offers for money laundering, Fake CSR bills or Reports. Kindly refrain from contacting us for such activities. Your wisdom and support in this will be highly appreciated.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div> */}

            <div className='MainPro5'>
                <p>We at RUDRAKSHA, are working on the Project Name “ARADHNARISHVAR” under the project head “GENDER JUSTICE”, to provide basic human rights and advantages to Women and Transgender with a motive of their identity upliftment. Women have played an extremely vital role in from the development of an individual to a nation on an elevated framework though ended up paying a hefty price in the form of her individuality and Equality. The depth of women respect and dignity is clearly mentioned in all ancient stories related to incarnation of Hindu Gods and their prominent followers. We can also find the same in other religious beliefs prevailing in this world though the irony of the situation is condition of women have been deteriorated in the last few decades at an alarming rate when it comes to equal opportunities and rights in all walks of lives.</p>
                <img src={require('../../Images/img1pro5.jpg')} /> 
                <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In Vedic India, since ages women in consortium of Hindu Religion, have been provided enough space for her safety, health, education, home, wealth which have declined since the time has changed towards new era for last several hundred years. The Brahmins (priestly people) used to provide enough Religious knowledge to the women of their families to have culture and religion being propagated to all sections of the society in more adequate ways. The Kshastriyas, (also called Rajanyas, who were rulers, administrators and warriors) used to provide fight skills training to their women, in order to make them strong enough to protect themselves and families in the hour of need. The Vaishyas (artisans, merchants, tradesmen and farmers) used to teach women of their families about trade tactics, farming techniques and art in order to assist them in their daily business activities. Finally the Shudras (laboring classes), used to make sure their women have adequate skills to help them in their work and earn more livelihoods for their families.
                In INDIA, we use to worship since Vedic era Gods in the form of ARDHNARISHWAR, which is none other the Supreme Lord of this Universe and a perfect combination of SHIVA and SHAKTI. The hypocrisy of human beings have deteriorated to such a depth in today’s world that they have deprived the same Shakti from her basic rights of equality in the daily routines of our lives. The only positive that comes out is that Government had been blessed with a group of good amount of wisdom think warehouses, which have made “Gender Equality one of the most prominent activity in all fields of society. We at RUDRAKSHA have aligned ourselves with this need of hour and have applied the same on us to begin with, describing a fraction of our intent towards this activity. The organizational manpower being hired represents close to 50% of female staff and same will be replicated in all the future offices opened in due course as per the need arises. As proud to be an Indian, we celebrate when a baby boy is born and if it's a girl then get muted by the culture. The disparity among children starts since they took birth, love for the boy and killing of girls. By other means, if she survives the first step of life, society has ways to discriminate her throughout life. As said, we pray to the goddess in temples, and we exploit girls.</p>

            </div>

            <div className='Main2Pro5'>
                <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Society is full of hypocrite people far from a right attitude towards women. In Indian constitution, gender equality is not a fundamental right, but it is one of the most crucial actions for prosperity, peace and sustainability. Since the last decade, the data shows more girls are now going to schools, less are getting married. Several laws have reformed to improve gender equality. According to UNICEF – gender equality means women or men; boys or girls enjoy the same rights, resources, opportunities and protection. Transgender persons (protection and Rights) act passed in 2019, which tells the misplaced understanding of gender and the limited equalizing potential of it. The transgender is one which didn’t assigned gender at the time of birth. This is mention in clause 2(k) of our Indian constitution. The main objective was to provide protection and rights to the transgender people, their welfare and in different fields. It was considered to be one of the bill which didn’t took much hours and debate. It has become an integral part of society.</p>
            <img src={require('../../Images/img2pro5.jpg')} /> 
            <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Transgender is considered to the gender identity, which is inconsistent or associated with any of the sex they assigned by birth and also deprived of the gender role. Transgender also cast a vote since the Supreme Court has declared them as the third gender. As our country is growing day by day, one of the significant changes is shown in the transgender figures. Aishwarya Rutaparna Pradhan born on Nov 12, 1983, became India's first openly transgender civil servant, working in the Odisha financial services as a commercial tax officer. Narthaki Natraj, a very well dancer from Tamil Nadu who has been honoured by Padma Shri, the 3rd highest civilian award. She is the first Indian to get this much of height. The Indian opposition party congress has appointed transgender Apsara Reddy to be the secretary of it women's wing the Mahila Congress. She is the first transgender person to come into the party of 134 years long history.
            Chandani Gore, is the deputy president of Nationalist congress party (NCP) in pune women’s wing. Kajal Nayak, a social activist from Jaipur also got the BSP ticket to contest the polls. In the growing phase, transgender is trying to accommodate in all the fields, be it entertainment too. Hrithik Roshan; has recently completed an Album with the Transgender Group & the same got appreciated at The Kapil Sharma Show on Sony Channel. A transgender actress and host Ganga has shown that with dedication, nothing is impossible to achieve success n ant field n today’s world. The INDIAN GOVERNMENT has taken many steps to help them in different field and sectors as they face various forms of gender violence, harassment and discrimination both in public and private places. Government is reserving seats for transgender in many fields. Reservations will have to be provided for transgender people in state police recruitments. For gender equality, the stability of every community is important. Proper utilization of resources, since ages, the patriarchal norms still prevail in our society where there is an apparent cut disparity between sexes. For a respected and better life- Women are treated and blamed for everything. On the contrary, males are called as superior in their all aspects. This is all because of the inequality existence. Ending all discrimination against women and girls is not only a basic human right, it’s crucial for sustainable future; it’s proven that empowering women and girls helps economic growth and development.</p>

            </div>

            <div className='Main3Pro5'>
                <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This is a matter of grave concern for our Nation and should not only be reminded on 26th Aug, being a National Women Equality Day” for a reason thereof. UNDP has made gender equality central to its work and we’ve seen remarkable progress in the past 20 years. There are more girls in school now compared to 15 years ago, and most regions have reached gender parity in primary education. In India, UN Women works closely with the Government of India and civil society to set national standards for achieving gender equality. UN Women works to strengthen women's economic empowerment through its support to women farmers and manual scavengers. The priority is also to make adequate arrangements to stop violence against women be it domestic, social or of any sort with a prime motive to provide them security and equal freedom.</p>
                <img src={require('../../Images/img3pro5.jpg')} /> 

                <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Women UN women also support gender equality parameters to be positive by providing women enough opportunities in the decision making roles in social and economic front for society and nation. The Government has contributed a lot and has provided enough support for such activities under the control and flagships of Ministry of Women and Child Development, GOI. State governments are the key to India’s progress on the SDG Agenda as they are best placed to ‘put people first’ and to ensuring that ‘no one is left behind’. Many of the Government’s flagship programmes such as Swachh Bharat, Make in India, Skill India, and Digital India are at the core of the SDGs. State and local governments play a pivotal role in many of these programs. Women generally have a natural wisdom and deep intellectual thought process of investing into their families, society, and nature way far ahead than a man can do. There have been decades when women trail behind men in forms of economic and social freedom, ownership rights, access to resources and opportunities though several evidences in today’s world have shown, giving equal opportunities for their growth have led to a better society and world for living. We have extended our support in the best possible way with in the limitations and compliances of instructions and guidelines being issued by GOI and hereby would like to seek the help from individuals, organizations, groups to participate in this holy activity of providing rights of equality to none other than who gives birth to men. We might involve other organizations, NGOs in our project(s) based on the need arises as per the situation. The preference will be through well established organization on State, Center or National Level which have positive track records. A strict compliance and due diligence will be followed as setup by Government for philanthropy organizations.</p>
            </div>

        </div>
        <FooterPagePro/>
        </>)
}

export default Pro5
