import React from 'react'
import FooterPagePro from '../Footer/Footer'
import HomeHeading from '../HomeHeading/HomeHeading'
import Navbar from '../Navbar/Navbar'
import "./Pro6.css"

function Pro1() {
  return (
      <>
      <HomeHeading/>
      <Navbar/>
    <div className='BodyPro1'>
            <div className='HeaderPro1'>
                <img src={require('../../Images/header6.jpg')} />


            </div>
            {/* <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Note:</strong> We don’t appreciate offers for money laundering, Fake CSR bills or Reports. Kindly refrain from contacting us for such activities. Your wisdom and support in this will be highly appreciated.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div> */}

            <div className='MainPro1'>
                <p>We at RUDRAKSHA, are working under the Project Name “VIKRIT VAIDHARMYA” under the Project Head “GRACIOUS JUSTICE”, to provide medical and emotional physiological support for Acid Survivors. An acid attack, also called acid throwing, vitriol attack, or vitriol age, is a form of violent assault involving the act of throwing acid or a similarly corrosive substance onto the body of another "with the intention to disfigure, maim, torture, or kill". The most common types of acid used in these attacks are sulfuric and nitric acid. Hydrochloric acid is sometimes used, but is much less damaging. Aqueous solutions of strongly alkaline materials, such as caustic soda (sodium hydroxide), are used as well, particularly in areas where strong acids are controlled substances. The long-term consequences of these attacks may include blindness, as well as eye burns, with severe permanent scarring of the face and body, along with far-reaching social, psychological, and economic difficulties. Today, acid attacks are reported in many parts of the world, though more commonly in developing countries. Between 1999 and 2013, a total of 3,512 Bangladeshi people was acid attacked with the rate of cases declining by 15%-20% every year since 2002 based on strict legislation against perpetrators and regulation of acid sales. In India acid attacks are at an all-time high and increasing every year with 250-300 reported incidents every year while the "actual number could exceed 1,000, according to Acid Survivors' Trust International".</p>
                <img src={require('../../Images/img6pro6.jpg')} />
                <p>   Acid attacks often occur as revenge against a woman who rejects a proposal of marriage or a sexual advance. Gender inequality and women's position in the society, in relation to men, plays a significant role in these types of attacks. Attacks against individuals based on their religious beliefs or social or political activities also occur. These attacks may be targeted against a specific individual, due to their activities, or may be perpetrated against random persons merely because they are part of a social group or community. Acid attacks in India, like Bangladesh, have a gendered aspect to them: analyses of news reports revealed at least 72% of reported attacks included at least one female victim. However, unlike Bangladesh, India's incidence rate of chemical assault has been increasing in the past decade, with a high 27 reported cases in 2010. Altogether, from January 2002 to October 2010, 153 cases of acid assault were reported in Indian print media while 174 judicial cases were reported for the year of 2000. The motivation behind acid attacks in India mirrors those in Bangladesh: a study of Indian news reports from January 2002 to October 2010 uncovered that victims’ rejected sex or marriage proposals motivated attacks in 35% of the 110 news stories providing a motive for the attack.</p>
            </div>

            <div className='Main2Pro1'>
                <p>Notable cases of acid attacks are Sonali Mukherjee's case of 2003 and Laxmi Agarwal in 2005. The latest crime data for 2018 from the National Crime Bureau (NCRB) shows acid attack cases are constantly getting transferred or sitting in police files year after year. This is shown by the data; in Indian courts 523 cases were slated for trial in 2018 which are up from 407 in 2016 and 442 in 2017. So, while total number of ‘registered’ cases in a particular year are on a slight decline, the fact that very few cases are disposed of in a year is symptomatic of how slow the justice system is. “There are so many more cases of acid attack that happen but never get filed especially in our hinterlands because in so many of these cases settlement happens outside the judiciary. Several other external factors like caste, class, power also come into play when registering such cases,” says Ashish Shukla of Chaanv Foundation.</p>
                <img src={require('../../Images/img7pro6.jpg')} />
                <p>
                    <ul>
                        <li>The percentage of cases of acid attacks that the courts disposed, of all the cases that went for trial, was 6.6 percent (27 cases out of 407) in the year 2016. It is only in 2017 that the percentage went up to 9.9 percent (44 cases out of 442). But, in 2018, it again came down to 6.11 percent cases (32 cases out of 523) reflecting that the system is unable to provide swift justice in the matter.</li>
                        <li>Total number of cases of acid attacks that police investigated dropped consistently between 2016 and 2018. It disposed of 196 cases in 2016, 182 in 2017 and 150 in 2018.</li>
                        <li>While the conviction rate in cases of acid attack and attempt to acid attack has increased in the last three years, the growth rate is almost negligible. In 2016, 2.45 percent cases (10 cases out of 407 cases) resulted in a conviction, as compared to 3.39 percent cases (15 cases out of 442) in 2017 and 3.36 percent cases (19 cases out of 523) in 2018.</li>
                    </ul>
                </p>
                <p>Uttar Pradesh and West Bengal have topped the list of states, reporting the greatest number of acid attack and attempt to acid attack cases between 2016 and 2018 as per the NCRB data. Among the 19 metropolitan cities recognized by the NCRB including Mumbai, Bengaluru, Kolkata, Ahmedabad, Chennai, Delhi etc, Delhi accounts for the highest number of cases filed. In 2016, when the total number of cases reported in the metropolitan cities was 29, Delhi alone recorded 18 cases. Subsequently, in 2017, 13 out of a total of 27 cases reported were from Delhi while in 2018, it registered 14 out of the 39 cases reported from metropolitan cities. In terms of convictions, there is a lot to be asked as well. The year 2015 saw the highest number of cases that went for trial - 734. At first glance, the conviction rate of 45.4 per cent looks better than other crimes against women. But out of the 734 cases that went for trial, only 33 were completed. The conviction rate is calculated as the percentage of cases convicted over trials completed. In 2016 and 2017, the conviction rate saw a decline with a total of 25 cases convicted out of 67 which completed trial, while a total of 849 cases were sent for trial in these two years. The year 2018 saw an upturn in conviction rate with a figure as high as 61 per cent, but out of 523 cases which went for trial, only 19 ended in conviction.</p>
            </div>

            <div className='Main3Pro1'>
                <img src={require('../../Images/img8pro6.jpg')} />
                <p>Sheroes Hangout is a cafe and community in India, run by survivors of acid attacks. The cafe aims to increase awareness of acid attacks and empower acid attack survivors. There are currently two cafe locations in Agra and Lucknow. The stop acid attack campaign by Sheroes was flagged on 8th March 2013 which is also celebrated as International Women’s Day to stand for acid attack survivors and against acid attacks in India. Their concept is to bridge between survivors and society. The first cafe, located in Agra, was opened in 2014 by Alok Dixit of Stop Acid Attacks, a non-profit based in New Delhi. Since that time, the cafe has expanded to open a second location in Lucknow. The cafe began as a crowdfunded project, and it operated with a pay what you want model. Early employees did not know how to run a restaurant, so they opted against setting prices, in case they made mistakes. This model remained in place for many years, but the cafe now features a fixed menu with fixed prices, as of 2020. The cafe is decorated with colourful murals, and there are books for customers to read on the bookshelves. A documentary on the cafe is available as well. Many of the patrons of the cafe are foreign tourists. The medical effects of acid attacks are extensive. As a majority of acid attacks are aimed at the face, several articles thoroughly reviewed the medical implications for these victims. The severity of the damage depends on the concentration of the acid and the time before the acid is thoroughly washed off with water or neutralized with a neutralizing agent. The acid can rapidly eat away skin, the layer of fat beneath the skin, and in some cases even the underlying bone. Eyelids and lips may be completely destroyed and the nose and ears severely damaged.</p>
                <p>The government has introduced a Central Victim Compensation Fund (CVCF) scheme, with an initial corpus of Rs 200 crores, to enable support to victims of rape, acid attacks, human trafficking and women killed or injured in the cross-border firing. Till now, there has been an absurd disparity in compensation amount paid by state governments varying from Rs 10,000 to Rs 10 lakh. Also, additional compensation of Rs. One lakh to the victims of acid attack under PMNRF is to be allocated in addition to the compensation under the Central Government Victim Compensation Fund Scheme (CVCF). Many non-governmental organizations (NGOs) have been formed in the areas with the highest occurrence of acid attacks to combat such attacks. Bangladesh has its Acid Survivors Foundation, which offers acid victims legal, medical, counselling, and monetary assistance in rebuilding their lives. NGOs provide rehabilitation services for survivors while acting as advocates for social reform, hoping to increase support and awareness for acid assault. Indian acid attack survivor Shirin Juwaley founded the Palash Foundation to help other survivors with psychosocial rehabilitation. She spearheads research into social norms of beauty and speaks publicly as an advocate for the empowerment of all victims of disfigurement and discrimination. In 2011, the principal of an Indian college refused to have Juwaley speak at her school for fear that Juwaley's story of being attacked by her husband would make students "become scared of marriage".</p>
                <p> We at RUDRAKSHA, will try to get them the best treatment, medical help by various sources of fundraising. Moreover, we will help them in legal matters, like case filing, lawyer meeting, case meetings, etc. We will try to provide them a source of income after their recovery so that they can at least earn their living and giving them their identity as it was before the attack. Will conduct certain counselling sessions in order to improve their mental health and teaching them various mind diverting exercises, meditation, yoga, etc. We hope these victims have a speedy recovery.</p>
            </div>

        </div>
        <FooterPagePro/>
        </> )
}

export default Pro1
