/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable no-unused-vars */
import React from "react";
import HomeHeading from "../HomeHeading/HomeHeading";
import Navbar from "../Navbar/Navbar";
import './Pro14.css'

function Pro14 ()
{
    return( 
    <>
    <HomeHeading/>
    <Navbar/>
    
    <div className="BodyPro14">
        <div className = "HeaderPro14">
        <img src={require('../../Images/img_14_1.jpg')} />
       </div>
       <div className='MainPro14'>
           <p>We at RUDRAKSHA, are working under the Project Name “PASHVIK MANGALYA” under the Project Name “VOICELESS SOULS”, to provide food, adaptation, shelter, medicinal and basic animal rights. Animals have always been considered sacred in our Hindu culture and they have been given importance equivalent to several Hindu Gods and Goddess in the form of their vehicles and associates. The Supreme Lord in Hindu religion, Lord MAHADEV, has been associated with animals like cow, bull, snakes and scorpions.The Goddess SHAKTI, has been given the supreme importance and has been associated with Lion. There are several such uncountable examples wherein people are worshipping and caring for animals as Holy and pure.The culture has always been enriched with and several examples wherein people use to feed them nurture them, protect them as per the weekdays which have been associated with them. This represents as in the culture of our human race, which have the oldest being HINDUS, on this universe have given importance to these speechless souls since millions of years.</p>
           <img src={require('../../Images/img_14_2.jpg')} />
           <p>We can take into consider any social animal like horses, cows, buffalos goats, monkeys, birds, underwater species etc. The same respect and dignity is being offered by other respected Religious beliefs in our country. This gives us a clear picture as in we have enough care and mercy for these poor souls since ages, though with the passage of time and modernization such thought process have been declined to some extent and people have literally started torturing these innocents for their personal benefit and tastes. Shows human needs can never get satisfied. The Vedas, the first scriptures of Hinduism, teach ahimsa which has setup certain cosmic rules for individuals to practice in order to attain a wealth of good Karmas. There has been a good amount of intervention from Government on this parameter as “Animal Welfare Right”, have been setup wherein strict compliance is being followed to make sure these souls should not be left helpless and merciless. The irony of the situation is people of this nation are not at all aware of the Animal Rights and they have to be advised and explained well in time before these souls end up losing faith in us. We generally use to remind a bit about their rights on 4th October being “World Animal Day”.
           India's first national animal welfare law, the Prevention of Cruelty to Animals Act, 1960, criminalizes cruelty to animals, though exceptions are made for the treatment of animals used for food and scientific experiments. The 1960 law also created the Animal Welfare Board of India to ensure the anti-cruelty provisions were enforced and promote the cause of animal welfare. In order to be more compliant, in this regard there has been few more laws which came into existence and have placed regulations and restrictions on the use of draught animals, the use of performing animals, animal transport, animal slaughter, and animal experimentation. The use of Animals for entertainment purposes in Circus, hurting them in movies, plays, street acts of any activity of the same sort or type has been banned completely by Government under the Protection of Animal Rights in Anti cruelty provisions. India has been good number of domestic animal welfare organizations who take care for animal welfare and protection for them at the hands of humans, though the most prominent activist who had been working in this area for the last several years is Ms. Maneka Gandhi, an animal rights activist, and environmentalist.</p>
           </div>

        <div className="Main2Pro14">
            <p>The latest incident which shows the cruelty of humans has increased in such a way that on 27th May 20; as some villagers had given a pineapple filled with firecrackers to an elephant who was pregnant. In Kerala, the elephant was wandering in search of food, trusting all humans to have a basic humanity but no, she was wrong to trust humans. The given food exploded in her mouth giving severe injuries in her jaws. She died in river. This problem didn’t ends here, animals like rhino and elephants suffer such inhumanly behaviors. Their parts get sell at very high rates more than of gold, diamond or cocaine. Even after strict restrictions of government. People brought pets at their home to safeguard their house or just for the fun but never have thought to those who are out. People throw waste including plastic everywhere and which is eaten by animals like cow, goat etc. Eventually they are not literate like us to make a comparison and get them killed.</p><br/>
            <img src={require('../../Images/img_14_3.jpg')} />
            <p>As the whole world is facing an acute problem of covid19 since the beginning of 2020; many foreign nations have their diet of eating animals like bat, snake, seal etc. which caused each and everyone to face the problem. The nationwide lockdown has shown that we are the reason; humans are the sole reason for the destruction of mother earth. We all are at our homes and so the animals are taking breath outside. The covid19 scenario beautifully portrayed that humans are the one needed to be live in cages not animals. While this time,now we see sky full of birds again. Not only have this throughout nation people seen many animals who was thriving at the time of reduced human activity. There is a serious cause of worry where in Zoos are generally not being maintained properly and corruption in the department and shortage of funds leads to bitter and cruel lives of several speechless souls who have been kept in this artificial habitat instead of their natural habitats, as forests have been declining at an alarming rate and they are bit safe in zoos at least from poachers.
            India's first national animal welfare law, the Prevention of Cruelty to Animals Act, 1960, criminalizes cruelty to animals, though exceptions are made for the treatment of animals used for food and scientific experiments. Article 51A (G) of The Constitution of India places a duty on every citizen to “protect and improve the natural environment including forests, lakes, rivers and wild life, and to have compassion for living creatures. The Prevention of Cruelty to Animals Act (PCA) was passed in 1960. Two large batches of rules under the PCA have been passed in the past 20 years, the first in 2001 and the second in 2017 and 2018. In 2001, rules pertaining to performing animals in circuses and movies, slaughterhouses, animal birth control, and the setting up of societies for the prevention of cruelty to animals (SPCA) were passed. In 2017 and 2018, rules on the regulation of shops that sell animals as pets, dog breeders, and livestock markets were passed. Animal Protection Laws are strict and can bring good amount of penalty and even prosecution if not followed by individuals. The implementation of these rules largely depends on the NGOs.</p>
        </div>
        
        <div className="Main3Pro14">
        <img src={require('../../Images/img_14_4.jpg')} />
            <p>A glimpse of such laws in favor of these souls is as follows:</p> <br/>
            <ul>
                  <li><b>The Delhi High Court states that there are no laws that prohibit people from feeding stray animals. In fact, feeding strays is both lawful and helpful since it makes it easy to confine them to one particular area that they belong to. This facilitates efficient birth control and annual vaccination.</b></li>
                  <li><b>It is a criminal offense to feed poisonous food to stray animals. A person who is caught doing so can be charged under Section 11 of the Prevention of Cruelty to Animals Act of 1960, which extends to the whole of India.</b></li>
                  <li><b>It is illegal to maim or cause any injury to any animal. Sections 428 and 429 of the Indian Penal Code and the Cruelty to Animals Act of 1960 make it illegal to maim or cause injury to any animal. It is also illegal for vehicles to purposefully injure dogs, cats and cows on the streets. A person who is caught violating these laws can be reported to the local animal protection group and to the police. A case can also be filed under the above mentioned sections.</b></li>
                  <li><b>No sterilized dogs can be relocated from their area. Under the Government of India, Animal Birth Control Rules 2001, no sterilized dogs can be relocated from their area. As per five different High Court Orders, sterilized dogs have to remain in their original areas. In case a dog is not sterilized, the society can just ask an animal welfare organization to sterilize and vaccinate the dog.</b></li>
                  <li><b>The Animal Welfare Board of India issues IDs for people who feed stray animals. These IDs help people who want to protect the strays from abusive animal-haters. The Board also organizes Animal Welfare Fortnight, which doesn’t gain the kind of attention that they should.</b></li>
                  <li><b>Stray dogs are protected under the Prevention of Cruelty to Animals Act, 1960, and rules enacted under Section 38 of the act, particularly, the Animal Birth Control (Dogs) Rules, 2001; Indian Penal Code, sections 428 & 429 and Article 51A (g) of the Constitution. Despite such extensive laws, people go free without punishment because bringing them to justice is a difficult task.</b></li>
            </ul>
            <p> We at RUDRAKSHA, have a motive behind this activity to save and protect the homeless animals from the cruelty been faced by them at the hands of few illiterate human beings and road accidents. We will be working religiously to stop the killing of animals wherever possible within the rules and regulations of the Government as per existing Animals Laws. The best portion of contribution for these types of activities comes in the form of volunteers, who step in from PAN INDIA in order to contribute towards food, care, protection of these poor souls. Our culture, family values and beliefs have been a great contributor in this respect. The awareness plays a major role and hence we come across several cow shelters, dog shelters, zoos, challans of animal cart holders, in case found guilty of cruelty. The awareness is yet to be spread into several sections of the society and we will make sure not to leave any stone unturned in order to achieve the same on regular basis. We might involve other organizations, NGOs in this project based on the need arises as per the situation. The preference will be through well established organization on State, Center or National Level which have positive track records. A strict compliance and due diligence will be followed as setup by Government for philanthropy organizations.</p>
           
        </div>
        
    </div>

    
    </>)}
export default Pro14